HMS/Areas/Dashboard/Controllers/AccommodationPackagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HMS.Services;
using HMS.Areas.Dashboard.ViewModels;
using HMS.Entities;
using HMS.ViewModels;
using HMS.Areas.Dashboard.Common;

namespace HMS.Areas.Dashboard.Controllers
{
    public class AccommodationPackagesController : Controller
    {
        AccommodationPackagesService APServices = new AccommodationPackagesService();
        AccommodationTypesService ATServices = new AccommodationTypesService();
        DashboardService DBServices = new DashboardService();

        // GET: Dashboard/AccommodationPackages
        public ActionResult Index(string searchTerm , int? accommodationTypeId , int? page)
        {
            int recordSize = 5;
            page = page ?? 1;

            AccommodationPackagesListingModel model = new AccommodationPackagesListingModel();

            model.SearchByName = searchTerm;
            model.SearchByAccommodationTypeId = accommodationTypeId;

            model.AccommodationPackages = APServices.GetAccommodationPackagesBySearch(searchTerm , accommodationTypeId , page.Value , recordSize);

            model.AccommodationTypes = ATServices.GetAllAccommodationTypes();

            var totalRecords = APServices.GetAccommodationPackagesCount(searchTerm,accommodationTypeId);

            model.Pager = new Pager(totalRecords, page, recordSize);

            return View(model);
        }

        // Create and Edite (Get view) 
        [HttpGet]
        public ActionResult Action(int? id)
        {
            AccommodationPackagesActionModel model = new AccommodationPackagesActionModel();

            if(id.HasValue) // edit
            {
                var apFromDB = APServices.GetAccommodationPackageById(id.Value);
                model.Id = apFromDB.Id;
                model.Name = apFromDB.Name;
                model.NoOfRoom = apFromDB.NoOfRoom;
                model.FeePerNight = apFromDB.FeePerNight;
                model.AccommodationTypeId = apFromDB.AccommodationTypeId;
                model.AccommodationPackagePictures = apFromDB.AccommodationPackagePictures;
            }

            model.AccommodationTypes = ATServices.GetAllAccommodationTypes();

            return PartialView("_Action", model);
        }

        // Create and Edite (Post view)
        [HttpPost]
        public JsonResult Action(AccommodationPackagesActionModel formModel)
        {
            bool result = false;

            //model.pictureIds = "22,23,24" => ["22","23","24"] => [22,23,24]
            var picsIds = !string.IsNullOrEmpty(formModel.PictureIds) ? formModel.PictureIds.Split(',').Select(int.Parse).ToList() : new List<int>();

            var pictures = DBServices.GetPicturesByIds(picsIds);

            if (formModel.Id == 0) //create
            {
                AccommodationPackage ap = new AccommodationPackage();

                ap.Name = formModel.Name;
                ap.NoOfRoom = formModel.NoOfRoom;
                ap.FeePerNight = formModel.FeePerNight;
                ap.AccommodationTypeId = formModel.AccommodationTypeId;

                ap.AccommodationPackagePictures = new List<AccommodationPackagePicture>();
                ap.AccommodationPackagePictures.AddRange(pictures.Select(p => new AccommodationPackagePicture()
                {
                    PictureId = p.Id
                }));

                result = APServices.AddAccommodationPackage(ap);
            }
            else //edit
            {
                var ap = APServices.GetAccommodationPackageById(formModel.Id);

                ap.Name = formModel.Name;
                ap.NoOfRoom = formModel.NoOfRoom;
                ap.FeePerNight = formModel.FeePerNight;
                ap.AccommodationTypeId = formModel.AccommodationTypeId;

                //delete existing accommodation pics to add new one after editing
                APServices.DeleteAccommdationPackagePictures(ap.Id);

                // in edit : need aPId to edit it not make a new one 
                ap.AccommodationPackagePictures.AddRange(pictures.Select(p => new AccommodationPackagePicture()
                {
                    AccommodationPackageId = ap.Id,
                    PictureId = p.Id
                }));

                result = APServices.UpdateAccommodationPackage(ap);
            }

            return JsonDataResult.Result(result);
        }

        // Delete 
        [HttpGet]
        public ActionResult Delete(int id)
        {
            AccommodationPackagesActionModel model = new AccommodationPackagesActionModel();

            var apFromDB = APServices.GetAccommodationPackageById(id);

            model.Id = apFromDB.Id;
            model.Name = apFromDB.Name;

            return PartialView("_Delete",model);
        }

        [HttpPost]
        public JsonResult Delete(AccommodationPackagesActionModel formModel)
        {
            var apFromDb = APServices.GetAccommodationPackageById(formModel.Id);

            bool result = APServices.DeleteAccommodationPackage(apFromDb);

            return JsonDataResult.Result(result);
        }
    }
}

HMS/Areas/Dashboard/Controllers/DashboardController.cs
using HMS.Entities;
using HMS.Services;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HMS.Areas.Dashboard.Controllers
{
    public class DashboardController : Controller
    {
        DashboardService DBServices = new DashboardService();

        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public JsonResult UploadPictures()
        {
            JsonResult jsonResult = new JsonResult();
            var picsList = new List<Picture>();

            var files = Request.Files;

            for (int i = 0; i < files.Count; i++)
            {
                var picture = files[i];
                var fileName = Guid.NewGuid() + Path.GetExtension(picture.FileName);
                var filePath = Server.MapPath("~/images/site/") + fileName;

                picture.SaveAs(filePath);

                var pictureDb = new Picture();
                pictureDb.URL = fileName;

                if (DBServices.SavePicture(pictureDb))
                {
                    picsList.Add(pictureDb);
                }
            }

            jsonResult.Data = picsList;
            return jsonResult;
        }
    }
}

HMS/Areas/Dashboard/Views/AccommodationPackages/Index.cshtml
@model HMS.Areas.Dashboard.ViewModels.AccommodationPackagesListingModel

@{
	ViewBag.Title = "Accommodation Packages";
}

<script src="~/Areas/Dashboard/Scripts/ViewScript.js"></script>

<div class="row">
	<div class="col col-lg-12">
		<h2>Accommodation Packages</h2>
		<hr />
	</div>
</div>

<div class="row mb-3">
	<div class="col col-lg-12">
		<form>
			<div class="input-group">
				<input type="text" name="searchTerm" class="form-control" placeholder="Search." value="@Model.SearchByName">

				@if (Model.AccommodationTypes != null && Model.AccommodationTypes.Count() > 0)
				{
					<select name="accommodationTypeId" class="form-control">
						<option value="0" selected>
							Select type.
						</option>
						 @foreach (var accommodationType in Model.AccommodationTypes)
							{
								<option value="@accommodationType.Id" @(Model.SearchByAccommodationTypeId == accommodationType.Id ? "selected" : string.Empty)>
									@accommodationType.Name
								</option>
							}
					</select>           
				}
			   
				<div class="input-group-append" id="button-addon4">
					<button class="btn btn-outline-primary" type="submit"><i class="fas fa-search mr-1"></i> Search</button>
					<a class="btn btn-outline-secondary" href="@Url.Action("Index","AccommodationPackages")"><i class="fas fa-redo-alt mr-1"></i> Reset</a>
					<button data-href="@Url.Action("Action", "AccommodationPackages")" class="action-btn btn btn-outline-success" type="button" data-toggle="modal" data-target="#actionModal"><i class="fas fa-plus mr-1"></i>Create</button>
				</div>
			</div>
		</form>
	</div>
</div>

<div class="row">
	<div class="col col-lg-12">
		@Html.Partial("_Listing", Model)

	</div>
</div>

<div class="modal fade" id="actionModal" tabindex="-1" role="dialog">
	<div class="modal-dialog" role="document">

	</div>
</div>

HMS/Areas/Dashboard/Views/AccommodationPackages/_Action.cshtml
@model HMS.Areas.Dashboard.ViewModels.AccommodationPackagesActionModel

@if (Model != null)
{
    <script src="~/Areas/Dashboard/Scripts/SaveActionWithPictures.js"></script>

    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title">
                @if (Model.Id == 0)
                {
                    <text> Create Accommodation Package </text>
                }
                else
                {
                    <text> Edit Accommodation Package </text>
                }
            </h5>

            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            <form id="actionForm">
                <input type="hidden" name="id" value="@Model.Id" />
                <div class="form-group">
                    <label>Name</label>
                    <input class="form-control" name="name" placeholder="Enter Accommodation Type name." value="@Model.Name">
                </div>
                <div class="form-group">
                    <label>No Of Rooms</label>
                    <input class="form-control" name="noOfRoom" placeholder="Enter No of rooms." value="@Model.NoOfRoom" type="number" />
                </div>
                <div class="form-group">
                    <label>Fee Per Night</label>
                    <input class="form-control" name="feePerNight" placeholder="Enter Fee per night." value="@Model.FeePerNight" type="number" />
                </div>
                <div class="form-group">
                    <label>Accommodation Type</label>

                    <select class="form-control" name="accommodationTypeId" required>
                        @if (Model.AccommodationTypes != null)
                        {
                            <option value="0" selected>
                                Select type.
                            </option>

                            foreach (var accommodationType in Model.AccommodationTypes)
                            {
                                <option value="@accommodationType.Id" @(accommodationType.Id == Model.AccommodationTypeId ? "selected" : string.Empty)>
                                    @accommodationType.Name
                                </option>
                            }
                        }
                    </select>
                </div>
                <div class="form-group">
                    <label>Pictures</label>
                    <input id="selectPictures" class="form-control-file" name="pictures" type="file" multiple pics-href="@Url.Action("UploadPictures","Dashboard")" />
                    <div style="text-align:center" class="mt-1">
                        <label id="deleteMsg" style="color:darkred; @( ( Model.AccommodationPackagePictures != null && Model.AccommodationPackagePictures.Count() != 0 )? string.Empty : "display:none" ) ">
                            Press on picture for deleting.
                        </label>
                    </div>
                    <input type="hidden" id="pictureIds" name="PictureIds" value="" />
                </div>
                <div id="picsArea">
                    @if (Model.AccommodationPackagePictures != null && Model.AccommodationPackagePictures.Count() > 0)
                    {
                        foreach (var aPP in Model.AccommodationPackagePictures)
                        {
                            <img src="/images/Site/@aPP.Picture.URL" width="230" class="img-thumbnail" data-id="@aPP.Picture.Id" onclick="removeMe(this)" />
                        }
                    }
                </div>
            </form>
            <div class="errorDiv"></div>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal"><i class="fas fa-times mr-1"></i>Close</button>
            <button id="saveActionBtn" data-href="@Url.Action("Action", "AccommodationPackages")" type="button" class="btn btn-primary"> <i class="fas fa-save mr-1"></i>Save</button>
        </div>
    </div>
}

<div id="picTemplate" hidden>
    <img src="" class="img-thumbnail" style="width:230px" onclick="removeMe(this)"/>
</div>

HMS/Areas/Dashboard/Views/AccommodationPackages/_Delete.cshtml
@model HMS.Areas.Dashboard.ViewModels.AccommodationPackagesActionModel

@if (Model != null)
{
    <script src="~/Areas/Dashboard/Scripts/DeleteActionScript.js"></script>
    
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title"> Delete Accommodation Package </h5>

            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            <form id="actionForm">
                <input type="hidden" name="id" value="@Model.Id" />
            </form>
            <div class="alert alert-danger" role="alert">
                Are you sure ? you wanna delete @Model.Name
            </div>
            <div class="errorDiv"></div>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal"><i class="fas fa-times mr-1"></i>Close</button>
            <button data-href="@Url.Action("Delete","AccommodationPackages")" href-target="@Url.Action("Index","AccommodationPackages")" id="deleteActionBtn" type="button" class="btn btn-danger">
                <i class="fas fa-trash-alt mr-1"></i>Delete
            </button>
        </div>
    </div>
}

HMS/Areas/Dashboard/Views/AccommodationPackages/_Listing.cshtml
@model HMS.Areas.Dashboard.ViewModels.AccommodationPackagesListingModel


@if (Model != null && Model.AccommodationPackages != null && Model.AccommodationPackages.Count() > 0)
{
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">Name</th>
                <th scope="col">Fee Per Night</th>
                <th scope="col">Accommodation Type</th>
                <th scope="col">Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var accommodationPackage in Model.AccommodationPackages)
            {
            <tr>
                <td> @accommodationPackage.Name</td>
                <td> @accommodationPackage.FeePerNight $</td>
                <td> @accommodationPackage.AccommodationType.Name</td>
                <td>
                    <button data-href="@Url.Action("Action", "AccommodationPackages", new { id = accommodationPackage.Id })" type="button" class="action-btn btn btn-primary" data-toggle="modal" data-target="#actionModal"><i class="fas fa-pen mr-1"></i> Edit</button>
                    <button data-href="@Url.Action("Delete", "AccommodationPackages", new { id = accommodationPackage.Id })" type="button" class="action-btn btn btn-danger" data-toggle="modal" data-target="#actionModal"><i class="fas fa-trash-alt mr-1"></i> Delete</button>
                </td>
            </tr>
            }
        </tbody>
    </table>

    if (Model.Pager.EndPage > 1)
    {
        <nav>
            <ul class="pagination">
                @if (Model.Pager.CurrentPage > 1)
                {
                    <li class="page-item">
                        <a class="page-link" href="@Url.Action("Index", "AccommodationPackages",
                        new
                        {
                            searchTerm = Model.SearchByName,
                            accommodationTypeId = Model.SearchByAccommodationTypeId
                        })">
                        <i class="fas fa-angle-double-left"></i>
                        </a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="@Url.Action("Index", "AccommodationPackages",
                        new
                        {
                            page = Model.Pager.CurrentPage - 1,
                            searchTerm = Model.SearchByName,
                            accommodationTypeId = Model.SearchByAccommodationTypeId
                        })">
                            <i class="fas fa-angle-left"></i>
                        </a>
                    </li>
                }

                @for (var page = Model.Pager.StartPage; page <= Model.Pager.EndPage; page++)
                {
                    <li class="page-item @(page == Model.Pager.CurrentPage ? "active" : "")">
                        <a class="page-link" href="@Url.Action("Index", "AccommodationPackages",
                        new
                        {
                            page = page,
                            searchTerm = Model.SearchByName,
                            accommodationTypeId = Model.SearchByAccommodationTypeId
                        })">@page</a>
                    </li>
                }

                @if (Model.Pager.CurrentPage < Model.Pager.TotalPages)
                {
                    <li class="page-item">
                        <a class="page-link" href="@Url.Action("Index", "AccommodationPackages",
                            new
                            {
                                page = Model.Pager.CurrentPage + 1,
                                searchTerm = Model.SearchByName,
                                accommodationTypeId = Model.SearchByAccommodationTypeId
                            })">
                            <i class="fas fa-angle-right"></i>
                        </a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="@Url.Action("Index", "AccommodationPackages",
                        new {
                            page = Model.Pager.TotalPages,
                            searchTerm = Model.SearchByName,
                            accommodationTypeId = Model.SearchByAccommodationTypeId
                        })">
                            <i class="fas fa-angle-double-right"></i>
                        </a>
                    </li>
                }
            </ul>
        </nav>
    }
}
else
{
    <div class="alert alert-warning" role="alert">
        Sorry! No records exist.
    </div>
}