HMS/Areas/Dashboard/Controllers/AccommodationTypesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HMS.Areas.Dashboard.ViewModels;
using HMS.Services;
using HMS.Entities;
using HMS.Areas.Dashboard.Common;

namespace HMS.Areas.Dashboard.Controllers
{
    public class AccommodationTypesController : Controller
    {
        AccommodationTypesService ATServices = new AccommodationTypesService();
        // GET: Dashboard/AccommodationTypes
        public ActionResult Index(string searchTerm)
        {
            AccommodationTypesListingModel model = new AccommodationTypesListingModel();

            model.SearchTerm = searchTerm;

            model.AccommodationTypes = ATServices.GetAccommodationTypesBySearch(searchTerm);

            return View(model);
        }

        [HttpGet]
        public ActionResult Action(int? id)
        {
            AccommodationTypesActionModel model = new AccommodationTypesActionModel();

            if (id.HasValue) //edit record
            {
                var accommodation = ATServices.GetAccommodationTypeById(id.Value); //note , value becuz it's nullable

                model.Id = accommodation.Id;
                model.Name = accommodation.Name;
                model.Description = accommodation.Description;
            }

            return PartialView("_Action", model);
        }

        [HttpPost]
        public JsonResult Action(AccommodationTypesActionModel formModel)
        {
            bool result = false;

            if(formModel.Id > 0) //edit record
            {
                var accommodationType = ATServices.GetAccommodationTypeById(formModel.Id);

                accommodationType.Name = formModel.Name;
                accommodationType.Description = formModel.Description;

                result = ATServices.UpdateAccommodationType(accommodationType);
            }
            else //create a new record
            {
                AccommodationType accommodationType = new AccommodationType();

                accommodationType.Name = formModel.Name;
                accommodationType.Description = formModel.Description;

                result = ATServices.SaveAccommodationType(accommodationType);
            }

            return JsonDataResult.Result(result);
        }

        //Delete Accommodation Type
        [HttpGet]
        public ActionResult Delete(int id)
        {
            AccommodationTypesActionModel model = new AccommodationTypesActionModel();

            var accommodation = ATServices.GetAccommodationTypeById(id);

            model.Id = accommodation.Id;
            model.Name = accommodation.Name;

            return PartialView("_Delete", model);
        }

        [HttpPost]
        public JsonResult Delete(AccommodationTypesActionModel formModel)
        {
            var accommodationType = ATServices.GetAccommodationTypeById(formModel.Id);

            bool result = ATServices.DeleteAccommodationType(accommodationType);

            return JsonDataResult.Result(result);
        }
    }
}

HMS/Areas/Dashboard/Views/AccommodationTypes/Index.cshtml
@model HMS.Areas.Dashboard.ViewModels.AccommodationTypesListingModel


@{
    ViewBag.Title = "Accommodation Type";
}

<script src="~/Areas/Dashboard/Scripts/ViewScript.js"></script>

<div class="row">
    <div class="col col-lg-12">
        <h2>Accommodation Types</h2>
        <hr />
    </div>
</div>

<div class="row mb-3">
    <div class="col col-lg-12">
        <form>
            <div class="input-group">
                <input type="text" name="searchTerm" class="form-control" placeholder="Search." required value="@Model.SearchTerm">
                <div class="input-group-append" id="button-addon4">
                    <button class="btn btn-outline-primary" type="submit"><i class="fas fa-search mr-1"></i> Search</button>
                    <a class="btn btn-outline-secondary" href="@Url.Action("Index","AccommodationTypes")"><i class="fas fa-redo-alt mr-1"></i> Reset</a>
                    <button data-href="@Url.Action("Action","AccommodationTypes")" class="action-btn btn btn-outline-success" type="button" data-toggle="modal" data-target="#actionModal"><i class="fas fa-plus mr-1"></i>Create</button>
                </div>
            </div>
        </form>
    </div>
</div>

<div class="row">
    <div class="col col-lg-12">
        @Html.Partial("_Listing",Model)

    </div>
</div>

<div class="modal fade" id="actionModal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">

    </div>
</div>

HMS/Areas/Dashboard/Views/AccommodationTypes/_Action.cshtml
@model HMS.Areas.Dashboard.ViewModels.AccommodationTypesActionModel

@if (Model != null)
{
    <script src="~/Areas/Dashboard/Scripts/SaveActionScript.js"></script>

    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title">
                @if (Model.Id == 0)
                {
                    <text> Create Accommodation Type </text>
                }
                else
                {
                    <text> Edit Accommodation Type </text>

                }
            </h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            <form id="actionForm">
                <input type="hidden" name="id" value="@Model.Id" />
                <div class="form-group">
                    <label>Name</label>
                    <input class="form-control" name="Name" placeholder="Enter Accommodation Type name." value="@Model.Name">
                </div>
                <div class="form-group">
                    <label>Description</label>
                    <textarea class="form-control" name="Description" placeholder="Enter Accommodation Type Description.">@Model.Description</textarea>
                </div>
            </form>
            <div class="errorDiv"></div>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal"><i class="fas fa-times mr-1"></i>Close</button>
            <button data-href="@Url.Action("Action","AccommodationTypes")" id="saveActionBtn" type="button" class="btn btn-primary"> <i class="fas fa-save mr-1"></i>Save</button>
        </div>
    </div>
}

HMS/Areas/Dashboard/Views/AccommodationTypes/_Delete.cshtml
@model HMS.Areas.Dashboard.ViewModels.AccommodationTypesActionModel


@if (Model != null)
{
    <script src="~/Areas/Dashboard/Scripts/DeleteActionScript.js"></script>

    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title">
                <span>Delete Accommodation Type</span>
            </h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            <form id="actionForm">
                <input type="hidden" name="id" value="@Model.Id" />
            </form>
            <div class="alert alert-danger" role="alert">
                Are you sure ? You wanna delete @Model.Name 
            </div>
            <div class="errorDiv"></div>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal"><i class="fas fa-times mr-1"></i>Close</button>
            <button data-href="@Url.Action("Delete","AccommodationTypes")" href-target="@Url.Action("Index","AccommodationTypes")" id="deleteActionBtn" type="button" class="btn btn-danger">
                <i class="fas fa-trash-alt mr-1"></i> Delete
            </button>
        </div>
    </div>
}

HMS/Areas/Dashboard/Views/AccommodationTypes/_Listing.cshtml
@model HMS.Areas.Dashboard.ViewModels.AccommodationTypesListingModel


@if (Model != null && Model.AccommodationTypes != null && Model.AccommodationTypes.Count() > 0)
{
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">Name</th>
                <th scope="col">Description</th>
                <th scope="col">Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var accommodationType in Model.AccommodationTypes)
            {
                <tr>
                    <td> @accommodationType.Name</td>
                    <td> @accommodationType.Description</td>
                    <td>
                        <button data-href="@Url.Action("Action", "AccommodationTypes", new { id = accommodationType.Id})" type="button" class="action-btn btn btn-primary" data-toggle="modal" data-target="#actionModal"><i class="fas fa-pen mr-1"></i> Edit</button>
                        <button data-href="@Url.Action("Delete", "AccommodationTypes", new { id = accommodationType.Id})" type="button" class="action-btn btn btn-danger" data-toggle="modal" data-target="#actionModal"><i class="fas fa-trash-alt mr-1"></i> Delete</button>
                    </td>
                </tr>

            }

        </tbody>
    </table>
}
else
{
    <div class="alert alert-warning" role="alert">
        Sorry! No records exist.
    </div>
}