HMS/ViewModels/AccommodationsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using HMS.Entities;

namespace HMS.ViewModels
{
    public class AccommodationsViewModel
    {
        public int SelectedAccommodationPackageId { get; set; }

        public AccommodationType AccommodationType { get; set; }
        public IEnumerable<AccommodationPackage> AccommodationPackages { get; set; }
        public IEnumerable<Accommodation> Accommodations { get; set; }
    }

    public class AccommodationPackageDetailsViewModel
    {
        public AccommodationPackage AccommodationPackage { get; set; }
    }

    public class CheckAccommodationAvailabilityViewModel
    {
        public int AccommodationPackageId { get; set; }

        public DateTime FromDate { get; set; }

        public int Duration { get; set; }

        public int NoOfAdults { get; set; }

        public int NoOfChildren { get; set; }

        public string Name { get; set; }

        public string Email { get; set; }

        public string Note { get; set; }
    }
}

HMS/Areas/Dashboard/Controllers/AccommodationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HMS.Services;
using HMS.Areas.Dashboard.ViewModels;
using HMS.Entities;
using HMS.ViewModels;
using HMS.Areas.Dashboard.Common;

namespace HMS.Areas.Dashboard.Controllers
{
    public class AccommodationsController : Controller
    {
        AccommodationsService AServices = new AccommodationsService();
        AccommodationPackagesService APServices = new AccommodationPackagesService();
        DashboardService DBServices = new DashboardService();

        // GET: Dashboard/Accommodations
        public ActionResult Index(string searchTerm, int? accommodationPackageId, int? page)
        {
            AccommodationsListingModel model = new AccommodationsListingModel();

            page = page ?? 1;
            var pageSize = 10;
            var totalRecords = AServices.GetAllAccommodationsCount(searchTerm, accommodationPackageId);

            model.Accommodations = AServices.GetAccommodationsBySearchOrPackageId(searchTerm, accommodationPackageId, page.Value, pageSize);

            model.SearchByName = searchTerm;
            model.SearchByAccommodationPackageId = accommodationPackageId;
            model.AccommodationPackages = APServices.GetAllAccommodationPackages();

            model.Pager = new Pager(totalRecords, page, pageSize);

            return View(model);
        }

        // create and edit (get)
        [HttpGet]
        public ActionResult Action(int? id)
        {
            AccommodationsActionModel model = new AccommodationsActionModel();

            if (id > 0) // edit
            {
                var accommodation = AServices.GetAccommodationById(id.Value);

                model.Id = accommodation.Id;
                model.Name = accommodation.Name;
                model.Description = accommodation.Description;
                model.AccommodationPackageId = accommodation.AccommodationPackageId;
                model.AccommodationPictures = accommodation.AccommodationPictures;

            }

            model.AccommodationPackages = APServices.GetAllAccommodationPackages();

            return PartialView("_Action", model);
        }

        // create and edit (post) 
        [HttpPost]
        public JsonResult Action(AccommodationsActionModel formModel)
        {
            bool result = false;

            var picsIds = string.IsNullOrEmpty(formModel.PictureIds) ? new List<int>() : formModel.PictureIds.Split(',').Select(int.Parse).ToList();

            var pictures = DBServices.GetPicturesByIds(picsIds);

            if (formModel.Id == 0) //create
            {
                //make instance of accommodation then fill it with the new data
                Accommodation accommodation = new Accommodation();

                accommodation.Name = formModel.Name;
                accommodation.Description = formModel.Description;
                accommodation.AccommodationPackageId = formModel.AccommodationPackageId;

                accommodation.AccommodationPictures = new List<AccommodationPicture>();
                accommodation.AccommodationPictures.AddRange(pictures.Select(p => new AccommodationPicture()
                {
                    PictureId = p.Id
                }));

                result = AServices.SaveAccommodation(accommodation);
            }
            else //edit
            {
                //get accommodation from db then modified it
                var accommodation = AServices.GetAccommodationById(formModel.Id);

                accommodation.Name = formModel.Name;
                accommodation.Description = formModel.Description;
                accommodation.AccommodationPackageId = formModel.AccommodationPackageId;

                //delete existing accommodation pics to add new one after editing
                AServices.DeleteAccommodationPictures(accommodation.Id);

                accommodation.AccommodationPictures.AddRange(pictures.Select(p => new AccommodationPicture() 
                { 
                    PictureId = p.Id, AccommodationId = accommodation.Id
                }));

                result = AServices.UpdateAccommodation(accommodation);
            }
            return JsonDataResult.Result(result);
        }

        // delete (get)
        [HttpGet]
        public ActionResult Delete(int id)
        {
            AccommodationsActionModel model = new AccommodationsActionModel();

            var accommodation = AServices.GetAccommodationById(id);

            model.Id = accommodation.Id;
            model.Name = accommodation.Name;

            return PartialView("_Delete", model);
        }

        // delete (post)
        public JsonResult Delete(AccommodationsActionModel formModel)
        {
            var accommodation = AServices.GetAccommodationById(formModel.Id);

            bool result = AServices.DeleteAccommodation(accommodation);

            return JsonDataResult.Result(result);
        }
    }
}

HMS/Controllers/AccommodationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HMS.Services;
using HMS.ViewModels;

namespace HMS.Controllers
{
    public class AccommodationsController : Controller
    {
        AccommodationTypesService ATServices = new AccommodationTypesService();
        AccommodationPackagesService APServices = new AccommodationPackagesService();
        AccommodationsService AServices = new AccommodationsService();

        public ActionResult Index(int accommodationTypeId , int? accommodationPackageId)
        {
            AccommodationsViewModel model = new AccommodationsViewModel();

            model.AccommodationType = ATServices.GetAccommodationTypeById(accommodationTypeId);

            model.AccommodationPackages = APServices.GetAllAccommodationPackagesByAccommodationType(accommodationTypeId);

            model.SelectedAccommodationPackageId  = accommodationPackageId.HasValue ? accommodationPackageId.Value : model.AccommodationPackages.First().Id;

            model.Accommodations = AServices.GetAllAccommodationsByAccommodationPackage(model.SelectedAccommodationPackageId);
            return View(model);
        }

        public ActionResult Details(int accommodationPackageId)
        {
            AccommodationPackageDetailsViewModel model = new AccommodationPackageDetailsViewModel();

            model.AccommodationPackage = APServices.GetAccommodationPackageById(accommodationPackageId);

            return View(model);
        }

        public ActionResult CheckAvailability(CheckAccommodationAvailabilityViewModel checkFormModel)
        {

            return View();
        }
    }
}

HMS/Views/Accommodations/Details.cshtml
@model HMS.ViewModels.AccommodationPackageDetailsViewModel

@using HMS.Entities;

@if (Model != null && Model.AccommodationPackage != null)
{

    var thumbnailPicture = Model.AccommodationPackage.AccommodationPackagePictures != null && Model.AccommodationPackage.AccommodationPackagePictures.Count > 0 ? Model.AccommodationPackage.AccommodationPackagePictures.First() : new AccommodationPackagePicture();

    var thumbnailURL = thumbnailPicture.Picture != null ? thumbnailPicture.Picture.URL : "default-image.jpg";

    <aside id="colorlib-hero">
        <div class="flexslider">
            <ul class="slides">
                <li style="background-image: url(/images/Site/@thumbnailURL);">
                    <div class="overlay"></div>
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-md-6 col-sm-12 col-md-offset-3 slider-text">
                                <div class="slider-text-inner slider-text-inner2 text-center">
                                    <h2>
                                        @Model.AccommodationPackage.AccommodationType.Name
                                    </h2>
                                    <h1>@Model.AccommodationPackage.Name</h1>
                                </div>
                            </div>
                        </div>
                    </div>
                </li>
            </ul>
        </div>
    </aside>


    <div id="colorlib-amenities">
        <div class="container">
            <div class="row">
                <div class="amenities-flex">
                    <div class="desc animate-box" style="width:1200px">
                        <p class="price">
                            <span class="currency">$</span>
                            <span class="price-room">@Model.AccommodationPackage.FeePerNight</span>
                            <span class="per">/ per night</span>
                        </p>
                        <p class="price">
                            <span class="free">@Model.AccommodationPackage.NoOfRoom rooms are available</span>
                        </p>

                        <p>
                            This accommodation package is from type @Model.AccommodationPackage.AccommodationType.Name
                            with many features like :
                            @Model.AccommodationPackage.AccommodationType.Description
                        </p>
                    </div>

                    @if (Model.AccommodationPackage.AccommodationPackagePictures != null && Model.AccommodationPackage.AccommodationPackagePictures.Count > 0)
                    {
                        foreach (var aPP in Model.AccommodationPackage.AccommodationPackagePictures)
                        {
                            var imageUrl = aPP.Picture != null ? aPP.Picture.URL : "default-image.jpg";
                            <div class="amenities-img animate-box" style="height:400px; background-image: url(/images/Site/@imageUrl);"></div>
                        }
                    }
                </div>
            </div>
        </div>
    </div>
}

<div id="colorlib-contact">
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1 animate-box">
                <h3>Booking</h3>
                <form  id="confirmBookingForm">

                    <input type="hidden" name="AccommodationPackageId" value="@Model.AccommodationPackage.Id" />

                    <div class="row form-group">
                        <div class="col-md-6">
                            <label for="fromDate">Check in date</label>
                            <input type="text" name="FromDate" id="fromDate" class="form-control" placeholder="Check in date" autocomplete="off">
                        </div>
                        <div class="col-md-6">
                            <label for="duration">Duration of stay nights</label>
                            <select id="duration" name="Duration" class="form-control">
                                @for (int i = 1; i <= 10; i++)
                                {
                                    <option value="@i">@i</option>
                                }
                            </select>
                        </div>
                    </div>

                    <div class="row form-group">
                        <div class="col-md-6">
                            <label for="noOfAdults">No of adults</label>
                            <input type="number" name="NoOfAdults" id="noOfAdults" class="form-control" value="1" min="1" max="10" autocomplete="off">
                        </div>
                        <div class="col-md-6">
                            <label for="noOfChildren">No of children</label>
                            <input type="number" name="noOfChildren" id="NoOfChildren" class="form-control" value="0" min="0" max="10" autocomplete="off">
                        </div>
                    </div>

                    <div class="row form-group">
                        <div class="col-md-6">
                            <label for="name">Guest Name</label>
                            <input type="text" id="name" name="Name" class="form-control" placeholder="Your name">
                        </div>
                        <div class="col-md-6">
                            <label for="email">Email</label>
                            <input type="text" id="email" name="Email" class="form-control" placeholder="Your email address">
                        </div>
                    </div>

                    <div class="row form-group">
                        <div class="col-md-12">
                            <label for="note">Add special note</label>
                            <textarea name="Note" id="note" cols="30" rows="10" class="form-control" placeholder="Add special note"></textarea>
                        </div>
                    </div>

                    <div class="form-group text-center">
                        <input type="button" id="checkAvailability" value="Check availability" data-href="@Url.Action("CheckAvailability","Accommodations")"  class="btn btn-primary">
                    </div>

                </form>
            </div>
        </div>
    </div>
</div>


 <script>
     $('#fromDate').datepicker({
         format: 'mm/dd/yyyy',
         startDate: '+3d'
     });

     $("#checkAvailability").click(function () {
         var linkUrl = $(this).attr("data-href");
         $.ajax({
             url: linkUrl,
             type: 'Post',
             data: $("#confirmBookingForm").serialize()
         })
         debugger;
     })

</script>

HMS/Views/Accommodations/Index.cshtml
@model HMS.ViewModels.AccommodationsViewModel

<aside id="colorlib-hero">
    <div class="flexslider">
        <ul class="slides">
            <li style="background-image: url(images/img_bg_5.jpg);">
                <div class="overlay"></div>
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-6 col-sm-12 col-md-offset-3 slider-text">
                            <div class="slider-text-inner slider-text-inner2 text-center">
                                <h2>Choose our Best</h2>
                                <h1> Hotel Rooms &amp; Apartments </h1>
                            </div>
                        </div>
                    </div>
                </div>
            </li>
        </ul>
    </div>
</aside>

@if (Model != null && Model.AccommodationPackages != null && Model.AccommodationPackages.Count() > 0)
{

    <div id="colorlib-rooms" class="colorlib-light-grey">
        <div class="container">
            <ul class="nav nav-tabs">
                @foreach (var ap in Model.AccommodationPackages)
                {
                    <li role="presentation" class="@(ap.Id == Model.SelectedAccommodationPackageId ? "active" : string.Empty)">
                        <a href="@Url.Action("Index", "Accommodations", new
                            {
                                area = "",
                                accommodationTypeId = Model.AccommodationType.Id,
                                accommodationPackageId = ap.Id
                            })">
                        @ap.Name
                        </a>
                    </li>
                }
            </ul>
            <br />
            <div class="row">
           
                @if (Model.Accommodations != null && Model.Accommodations.Count() > 0)
                {
                    foreach (var accommodation in Model.Accommodations)
                    {
                        <div class="col-md-4 room-wrap animate-box">
                            <a href="images/room-1.jpg" class="room image-popup-link" style="background-image: url(images/room-1.jpg);"></a>
                            <div class="desc text-center">
                                <span class="rate-star"><i class="icon-star-full full"></i><i class="icon-star-full full"></i><i class="icon-star-full full"></i><i class="icon-star-full"></i><i class="icon-star-full"></i></span>
                                <h3>
                                    <a href="rooms-suites.html">
                                        @accommodation.Name
                                    </a>
                                </h3>
                                <p class="price">
                                    <span class="currency">$</span>
                                    <span class="price-room">@accommodation.AccommodationPackage.FeePerNight</span>
                                    <span class="per">/ per night</span>
                                </p>
                                <ul>
                                    <li><i class="icon-check"></i> @accommodation.AccommodationPackage.NoOfRoom </li>
                                </ul>
                                <p><a class="btn btn-primary">Book now!</a></p>
                            </div>
                        </div>
                    }
                }
                else
                {
                    <div class="alert alert-warning" role="alert">
                        No Accommodations Found.
                    </div>
                }
            </div>
        </div>
    </div>
}